export const API_ENDPOINTS = {
  PRODUCTS: '/api/v1/products',
  PRODUCT_DETAILS: (id: string) => `/api/v1/products/${id}`,
  PRODUCT_COMPARISON: (id: string) => `/api/v1/products/${id}/comparison`,
  FEATURED_PRODUCTS: '/api/v1/products/featured',
  CATEGORIES_STRUCTURE: '/categories/structure',
  CATEGORIES_TREE: '/categories/tree',
  CATALOG_FAMILIES: '/catalog/families',
  CATALOG_FAMILY_ITEM: '/catalog/families/item',
  CATALOG_FAMILY_BRANDS: '/catalog/families/brands',
  LIVE_SEARCH: '/search/live',
  ADMIN_GROUP_CODE_ENSURE: '/admin/group-codes/ensure',
  ADMIN_GROUP_CODE_LINK: '/admin/group-codes/link',
  ADMIN_GROUP_CODE_UNLINK: '/admin/group-codes/unlink',
  ADMIN_GROUP_CODE_MERGE: '/admin/group-codes/merge',
  ADMIN_GROUP_CODE_SUGGESTIONS: (code: string) => `/admin/group-codes/${encodeURIComponent(code)}/suggestions`,
  ADMIN_PHARMACY_PRODUCT_SEARCH: '/admin/pharmacy-products/search',
  ADMIN_MASTER_PRICE_SYNC: (id: string) => `/admin/masters/${id}/price-sync`,
  ADMIN_MASTER_BARCODE: (id: string) => `/admin/masters/${id}/barcode`,
  AUTH_LOGIN: '/api/v1/auth/login',
  AUTH_ME: '/api/v1/auth/me',
  AUTH_LOGOUT: '/api/v1/auth/logout',
  AUTH_REGISTER: '/api/v1/auth/register',
  AUTH_VERIFY_REGISTER_CODE: '/api/v1/auth/verify-register-code',
  AUTH_FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
  AUTH_VERIFY_RESET_CODE: '/api/v1/auth/verify-reset-code',
  AUTH_RESET_PASSWORD: '/api/v1/auth/reset-password',
  AUTH_CHANGE_PASSWORD: '/api/v1/auth/change-password',
  BILLBOARDS: '/api/v1/billboards',
  BILLBOARD: (id: string) => `/api/v1/billboards/${id}`,
  BILLBOARD_IMAGE: '/api/v1/billboards/image',
  BILLBOARDS_MOBILE_ACTIVE: '/api/v1/billboards/mobile/active',
  MAGAZINES: '/api/v1/magazines',
  MAGAZINE: (id: string) => `/api/v1/magazines/${id}`,
  MAGAZINE_COVER: '/api/v1/magazines/cover',
  MAGAZINE_PDF: '/api/v1/magazines/pdf',
  MAGAZINES_MOBILE_ACTIVE: '/api/v1/magazines/mobile/active',
  COUPONS: '/api/v1/coupons',
  COUPON: (id: string) => `/api/v1/coupons/${id}`,
  PHARMACY_SEARCH_VISIBILITY: '/api/v1/pharmacies/search-visibility',
  PHARMACY_SEARCH_VISIBILITY_BASE: '/api/v1/pharmacies',
  PHARMACY_PRICE_SYNC: (id: string) => `/api/v1/pharmacies/${id}/price-sync`,
  PHARMACY_CATALOG_XLSX: (id: string) => `/api/v1/pharmacies/${id}/catalog.xlsx`,
  CUSTOMER_SEARCH: '/api/v1/customer/search',
  CUSTOMER_SEARCH_ITEM: '/api/v1/customer/search/item',
  CUSTOMER_SEARCH_BRANDS: '/api/v1/customer/search/brands',
  CUSTOMER_SEARCH_RECENT: '/api/v1/customer/search/recent',
  CUSTOMER_PRODUCTS: '/api/v1/customer/products',
  CUSTOMER_ADS: '/api/v1/customer/ads',
  CUSTOMER_CATEGORIES: '/api/v1/customer/categories',
  CUSTOMER_FEATURED: '/api/v1/customer/featured',
  CUSTOMER_PHARMACIES: '/api/v1/pharmacies/customer-search',
  ADMIN_USERS: '/api/v1/admin/users',
  ADMIN_MATCH_REVIEWS: '/api/v1/admin/match-reviews',
  ADMIN_MATCH_REVIEW: (id: string) => `/api/v1/admin/match-reviews/${id}`,
  ADMIN_MATCH_REVIEW_ACCEPT: (id: string) => `/api/v1/admin/match-reviews/${id}/accept`,
  ADMIN_MATCH_REVIEW_REJECT: (id: string) => `/api/v1/admin/match-reviews/${id}/reject`,
  ADMIN_MATCH_REVIEW_FORCE: (id: string) => `/api/v1/admin/match-reviews/${id}/force-match`,
  ADMIN_MATCH_REVIEW_BULK: '/api/v1/admin/match-reviews/bulk',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_CONTENT: '/api/v1/admin/content',
  ADMIN_LOGS: '/api/v1/admin/logs',
  CUSTOMER_CONTENT_STATUS: '/api/v1/content/status',
  CUSTOMER_CONTENT_HELP: '/api/v1/content/help',
  CUSTOMER_CONTENT_TERMS: '/api/v1/content/terms',
  DEALS_BEST: '/deals/best',
  ADMIN_DEALS_SETTINGS: '/api/v1/admin/deals/settings',
  ADMIN_DEALS_REFRESH_CACHE: '/api/v1/admin/deals/refresh-cache',
  ADMIN_DEALS_TOGGLE_PIN: '/api/v1/admin/deals/toggle-pin',
  ADMIN_DEALS_TOGGLE_EXCLUDE: '/api/v1/admin/deals/toggle-exclude',
  ADMIN_CATEGORY_IMAGE: (id: string) => `/api/v1/admin/categories/${id}/image`,
  ADMIN_PRODUCT_IMAGES: (id: string) => `/api/v1/admin/products/${id}/images`,
  ADMIN_PRODUCT_IMAGE: (id: string) => `/api/v1/admin/products/${id}/image`,
  ADMIN_PRODUCT_IMAGE_URL: (id: string) => `/api/v1/admin/products/${id}/image-url`
} as const;
